### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by NaBuchholz** [labenuexercicios/projeto-frontendreact#116]
add the functionality of add and see items in the cart

**Comment by KarineMarsi** [comment]
Parabéns pela entrega!
## Requisitos do projeto ✅
Implementações | Feito
--- | :---:
(Lista de Produtos) O usuário deve ser capaz de visualizar uma lista de produtos | ✅
(Lista de Produtos) O usuário deve ser capaz de visualizar os dados do produto (nome, preço e imagem) | ✅
(Lista de Produtos) O usuário deve ser capaz de adicionar um produto no carrinho | ✅
(Carrinho) O usuário deve ser capaz de visualizar os produtos adicionados | ✅
(Carrinho) O usuário deve ser capaz de visualizar a quantidade correta de cada produto | ✅
(Carrinho) O usuário deve ser capaz de remover itens do carrinho | ✅
(Carrinho) O usuário deve ser capaz de ver corretamente o valor total de sua compra | ✅
(Carrinho) Quando a página é atualizada, os itens devem continuar no carrinho | -
(Filtros e Ordenação) O usuário deve ser capaz de filtrar os itens por preço mínimo | ✅
(Filtros e Ordenação) O usuário deve ser capaz de filtrar os itens por preço máximo | ✅
(Filtros e Ordenação) O usuário deve ser capaz de realizar uma busca por nome | ✅
(Filtros e Ordenação) O usuário deve ser capaz de ordenar os itens em ordem crescente ou decrescente | ✅
(Filtros e Ordenação) O usuário deve ser capaz de adicionar filtros, busca e ordenação simultaneamente | ✅
(Filtros e Ordenação) O usuário deve ser capaz de retornar à visualização sem filtros | ✅
![Ahazou](https://user-images.githubusercontent.com/93096599/221196087-909e48f3-823f-4eab-8e7a-96997ba87c21.png)
